language: csharp
mono: none
dotnet: 2.0.0
branches:
 only:
  - master
script:
  - dotnet build ./ContactList.WebApi/ContactList.sln -c Release
deploy:
  provider: s3
  access_key_id: AKIAIU44V3FCYOTPWKCQ
  secret_access_key: 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
  bucket: uniqbucketname1999
