language: csharp
mono: none
dotnet: 2.0.0
branches:
 only:
  - master
script:
  - dotnet build ./ContactList.WebApi/ContactList.sln -c Release
  travis setup releases
deploy:
      - provider: s3
      - provider: codedeploy
        access_key_id: accesskeyid
        secret_access_key: secretaccesskey
        bucket: uniqbucketname1999
        key: latest/ContactList.zip
        application: ContactList
        deployment_group: Unit
