language: csharp  
sudo: required
dist: trusty
mono: none
dotnet: 2.0.0
branches:
 only:
  - master
script:
  - dotnet restore
  - dotnet build "ContactList/ContactList.sln" -c Debug -f netcoreapp2.0
